apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backfill-redis
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/securesign-tenant/rekor/backfill-redis@sha256:6993d7b368dd27a556255fc547120eee2659690d1bce98ee7db8e3b52493b460
        name: container-image
        resources: {}
status: {}
