apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rekor-cli
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/securesign-tenant/rekor/rekor-cli@sha256:443e2bb87329e8c58eed038fecf4aa4e50e64727c607890e1b7bdb79d35e36b7
        name: container-image
        resources: {}
status: {}
