apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rekor-cli
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/securesign-tenant/rekor/rekor-cli@sha256:9edc510df821c19441786b4171db83b07c75941ae87a418f961366a4aa420022
        name: container-image
        resources: {}
status: {}
