apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backfill-redis
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backfill-redis
    app.kubernetes.io/part-of: rekor
  name: backfill-redis
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: backfill-redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: backfill-redis
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/securesign-tenant/rekor/backfill-redis@sha256:6993d7b368dd27a556255fc547120eee2659690d1bce98ee7db8e3b52493b460
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
